baithi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from inside import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'inside/', include('inside.urls')),
    path(r'cart/', include('cart.urls')),
    path(r'social-auth/', include('social_django.urls', namespace="social")),
    path(r'orders/', include('orders.urls')),
    path(r'accounts/', include('allauth.urls')),
    path(r'booking/', include('bookingsite.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

inside/urls.py
from django.conf.urls import url
from inside import views

app_name = 'inside'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'signin', views.signin, name = 'signin'),
    url(r'signup', views.signup, name = 'signup'),
    url(r'logout', views.user_logout, name = 'logout'),
    url(r'chi-tiet/(\d+)$', views.chiTiet,name='chi-tiet'),
    url(r'registered', views.Registration,name='registered'),
]

inside/models.py
from django.db import models
from django.contrib.auth.models import User as UserAdmin
# Create your models here.

class SanPham(models.Model):
    id=models.AutoField(primary_key=True)
    ten_san_pham=models.CharField('Ten san pham', max_length=200, unique=True)
    hinh = models.ImageField('Hinh', upload_to='hinh_san_pham', blank=True)
    don_gia_ban = models.FloatField('Don gia')
    mo_ta_tom_tat = models.CharField('Tom tat', max_length=200)
    chi_tiet = models.TextField('Chi tiet')
    trang_thai = models.BooleanField('Trang thai',blank=True, default=True)
    def __str__(self):
        return self.ten_san_pham

class User(models.Model):
    name = models.CharField(max_length=255, unique = True)
    email = models.EmailField()
    password = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        db_table = u'User'

class UserProfileInfo(models.Model):
    user = models.OneToOneField(UserAdmin, on_delete=models.PROTECT)
    portfolio = models.URLField(blank = True)
    picture = models.ImageField(upload_to="images/", blank = True)

    def __str__(self):
        return self.user.username

inside/forms.py
from django import forms
from inside.models import User
from .models import UserProfileInfo
from django.contrib.auth.models import User as UserAdmin

class FormRegister(forms.ModelForm):
    name = forms.CharField(label='Your name', max_length=100)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['name', 'email', 'password']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = UserAdmin
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    picture = forms.ImageField(required = False)
    class Meta():
        model = UserProfileInfo
        exclude = ('user', )

inside/views.py
from django.shortcuts import render
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from inside.models import SanPham
from datetime import datetime
from inside.models import User
from . import forms
from cart.forms import CartAddProductForm
from django.contrib.auth import authenticate 
from django.contrib.auth import login
from django.contrib.auth import logout  

# Create your views here.
def index(request):
    SanPham_list = SanPham.objects.all()
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits+1

    response = render(request, "inside/index.html", {'sanpham_list':SanPham_list, 'num_visits':num_visits})
    date1 = datetime.now()
    response.set_cookie("last_visit", date1.strftime('%d-%m-%Y %H:%M:%S'))
    last_visit = request.COOKIES.get('last_visit')

    return render(request, "inside/index.html", {'sanpham_list':SanPham_list, 'num_visits':num_visits, 'last_visit': last_visit})

def signin(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                result = "WELCOME " + username
                return render(request, "inside/signin.html", {"result": result})
        else:
            print("Cannot Login")
            print("Username: {} and Password: {}".format(username, password))
            login_result = "Username and Password are not valid"
            return render(request, "inside/signin.html", {"result": login_result})
    else:
        return render(request, "inside/signin.html")

def user_logout(request):
    logout(request)
    result = "You have logged out, Please choose  SIGN IN"

    return render(request, "inside/logout.html", {"result":result})

def signup(request):
    form = forms.FormRegister()
    if request.method == 'POST':
        form =forms.FormRegister(request.POST, User)

        if form.is_valid() and form.cleaned_data['password'] == form.cleaned_data['confirm']:
            request.POST._mutable = True
            post = form.save(commit = False)
            post.name = form.cleaned_data['name']
            post.email = form.cleaned_data['email']
            post.password = form.cleaned_data['password']
            post.save()
            print("Saved to database")

        elif form.cleaned_data['password'] != form.cleaned_data['confirm']:
            form.add_error('confirm', 'The password does not match')
            print("Not confirm!")
    return render(request, "inside/signup.html", {'form': form})

def chiTiet(request, id):
    sanPham = SanPham.objects.get(id=id)
    cart_product_form = CartAddProductForm()
    return render(request,'inside/chitiet.html',{'sanPham':sanPham, 'cart_product_form': cart_product_form})

def Registration(request):
    registered = False 
    if request.method == 'POST':
        form_user = forms.UserForm(data= request.POST)
        form_por = forms.UserProfileInfoForm(data= request.POST)
        if form_user.is_valid() and form_por.is_valid():
            user = form_user.save()
            user.set_password(user.password)
            user.save()

            profile = form_por.save(commit = False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()

            registered = True
        else:
            print(form_user.errors, form_por.errors)

    else:
        form_user = forms.UserForm()
        form_por = forms.UserProfileInfoForm()

    return render(request, 'inside/registration.html', {'user_form': form_user, 'profile_form': form_por, 'registerd': registered})

templates/inside/chitiet.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Details</title>

    <!-- Custom fonts for this theme -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">

    <!-- Theme CSS -->
    <link href="{% static 'css_js' %}/css/freelancer.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">

</head>

<body>

    <!-- Header -->

    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">ORDER</a>
            <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:index' %}">Products</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:index' %}">About</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:index' %}">Contact</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:signin' %}">Sign in</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:signup' %}">Sign up</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- End Header -->

    <!-- Begin #services-section -->
    <span style="display:inline-block; width: 500;"></span>
    <section class="page-section portfolio" id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <img width="240" height="260" src="{{sanPham.hinh.url}}" />
                </div>
                <div class="post_text form-inline">
                    <p class="services-body">Description: {{sanPham.chi_tiet}}</p>
                    <p class="services-body">Products on store: {{sanPham.trang_thai}}</p>
                </div>
                <form action="{% url 'cart:cart_add' sanPham.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-inline">
                        <label>
                            <input type = "radio" name = "Th_don_gia" value = "{{sanPham.don_gia_ban}}" checked /> Price: {{sanPham.don_gia_ban}} VND
                        </label>

                    </div>
                    <div class="post_text form-inline">

                        {{cart_product_form.quantity}}
                        <input type="submit" value="Add to cart" class="btn btn-success" style="margin-left:10px">

                    </div>


                </form>
            </div>

        </div>
    </section>
    <!-- End #services-section -->


    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">

                <!-- Footer Location -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Location</h4>
                    <p class="lead mb-0">541/2 Nguyen Tri Phuong
                        <br>Ward 8, District 10, Ho Chi Minh city</p>
                </div>

                <!-- Footer Social Icons -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Back to front</h4>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-facebook-f"></i>
                    </a>

                </div>

                <!-- Footer About Text -->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">About CK Bookstore</h4>
                    <p class="lead mb-0">CK Bookstore is free for everyone who would like to share, sell books or just discuss and find some new books
                        <a href="http://tiki.vn">Start CK Bookstore</a>.</p>
                </div>

            </div>
        </div>
    </footer>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Copyright &copy; Your Website 2019</small>
        </div>
    </section>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
        <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <script type="text/javascript" src="{% static 'css_js' %}/js/jquery-1.10.2.min.js"></script>
    <script src="{% static 'css_js' %}/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="{% static 'css_js' %}/js/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>
</body>

</html>

templates/inside/logout.html
<!doctype html> {% extends "base.html" %} {% block content %} {% load staticfiles %}
<div class="container">
    <h1> Logout </h1>
    <div class="container">
        <font color="red">{{result}}</font>
    </div>
</div>
{% endblock %}

templates/inside/registration.html
{% extends 'base.html' %} {% block content %}

<!-- Begin Service-section -->
<section id="services" class="services-section section-global-wrapper">
    <div class="container">
        <div class="row">
            {% if registered %}
            <h3> Thank you for your official registration ! - Your account has been saved</h3>
            {% else %}
            <h3> REGISTER HERE - BY FILLING THE FORM </h3>

            <table>
                <form method='POST' enctype="multipart/form-data">
                    {% csrf_token %} {% for field in user_form %}
                    <tr>
                        <td> {{field.label}} </td>
                        <td> {{field}} </td>
                    </tr>
                    {% endfor %} {% for field in profile_form %}
                    <tr>
                        <td> {{field.label}} </td>
                        <td> {{field}} </td>
                    </tr>
                    {% endfor %}

                    <tr>
                        <td colspan="2">
                            <input type="submit" class="btn btn-primary" value="Register">
                        </td>
                    </tr>

                </form>
            </table>
        </div>
        {% endif %}
    </div>
    </div>
</section>

{% endblock %}

templates/inside/signin.html
<!doctype html> {% extends "base.html" %} {% block content %} {% load staticfiles %}{% load socialaccount %}

<div class="container">
    <a>{{last}}</a>
    <h1> Login </h1>
    <form method="POST" action="{% url 'inside:signin' %}">
        <table>
            <tr>
                <td>
                    <lable for="username">Username: </lable>
                </td>
                <td><input type="text" name="username" placeholder="Enter Username">
                </td>
            </tr>

            <tr>
                <td>
                    <lable for="password">Password: </lable>
                </td>
                <td><input type="password" name="password" placeholder="Enter Password"></td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" class="btn btn-primary" value="Submit">
                </td>
            </tr>
        </table>
        {% csrf_token %}
    </form>
</div>
<div class="container">
    <font color="red">{{result}}</font>
</div>

<button class="btn btn-primary">
    <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
</button>


<button class="btn btn-primary">
    <a href="{% provider_login_url 'google' %}">Login with Google</a> 
</button> {% endblock %} {% load socialaccount %}

templates/inside/signup.html
{% load staticfiles %}


<div class='row'>
    <form method="post">
        {{form.as_p}} {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>
</div>